### ISSUE TITLE
Compiler crash on invalid semicolon syntax

### ISSUE THREAD

**Issue by fmease** [faiface/funky#4]
The following malformed input causes the compiler to crash:
```funky
func main : IO = ;
```
Output:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x4e3bd8]

goroutine 1 [running]:
github.com/faiface/funky/parse.treeToFunc(0x575340, 0xc0002b64a0, 0xc0002b6460, 0xc0001eba30, 0x4, 0x4, 0x575340, 0xc0002b64a0)
	/home/fmease/.go/src/github.com/faiface/funky/parse/definitions.go:249 +0x158
github.com/faiface/funky/parse.TreeToDefinitions(0x575380, 0xc0002b8990, 0x8, 0x575380, 0xc0002b8990, 0x0, 0x0)
	/home/fmease/.go/src/github.com/faiface/funky/parse/definitions.go:60 +0x3ae
github.com/faiface/funky/parse.Definitions(0xc0000ab080, 0x6, 0x8, 0x0, 0xc0000ab080, 0x6, 0x8, 0x0)
	/home/fmease/.go/src/github.com/faiface/funky/parse/definitions.go:20 +0x92
github.com/faiface/funky.Run(0x54a6a2, 0x4, 0x54a626, 0x4)
	/home/fmease/.go/src/github.com/faiface/funky/run.go:58 +0x1454
main.main()
	/home/fmease/.go/src/github.com/faiface/funky/interpreters/funkycmd/main.go:14 +0x4b
```

Further information: The semicolon "applied" to only one instead of two arguments (`0;` and `;0`) behaves like the identity function. If "applied" to zero arguments, it is treated as if it is not actually there provided it's preceded by an expression which resolves to a value. `0 (;)` is treated as `0`, `self (;) 0` as `self 0` and so on. Contrarily, expressions like `(;) (;) (;)` and `(;) 0` cause a crash.

**Comment by faiface** [comment]
Thanks again! I'll try and fix all the issues you reported shortly. If you find more, please submit!
